Makes testable and add the ability to pre-fill configuration values
alarner/config-template pull request #5
Opened 2016-10-11 20:00 UTC by aurium

2016-10-31 20:26 UTC, aurium commented
Hi @alarner! Is this fine?

2016-11-03 04:23 UTC, alarner commented
@aurium sorry it's taken me so long to get to this. I"m taking a look at it tonight but it's taking longer than I expected because my old code was so bad :) I'm trying to remember how this thing works and also trying to understand the changes that you made. Thank you sooooo much for adding tests. That's making my life a whole lot easier right now. Hopefully I'll be able to merge this week.

2016-11-03 04:38 UTC, alarner requested changes
Overall this is fantastic work. Just a few requests based on my understanding of what you've done here. If I'm misunderstanding something let me know and we can discuss. If you're too busy / don't want to make these changes just let me know and I can finish things up. I'm so excited to merge this in!

2016-11-03 04:38 UTC, alarner commented on index.js
> +function setDefaultValues(parsedTmpl, values) {
Can we re-write this function like this?
```js
function setDefaultValues(parsedTmpl, values) {
	for (let i=0; i<parsedTmpl.lines.length; i++) {
		const line = parsedTmpl.lines[i];
		let obj = values;
		for(let j=0; j<line.path.length; j++) {
			obj = obj[line.path[j]];
		}
		line.value = obj.toString();
	}
}
```

It's a little bit more code but I think it's more clear what's going on than with multiple variables changing inside each for loop.

2016-11-03 04:38 UTC, alarner commented on index.js
> +		if(!_.isString(obj) || !obj.match(helpRegex)) {
It seems like this work is more suited to be done in the appendExtraData function. This way our template doesn't have a mix of instructions strings (eg. '[string] Defaults to "The environment."') and value strings (eg. 'The environment.')

2016-11-03 04:38 UTC, alarner commented on test/config-template.test.js
> +var should = require('chai').should();
These tests are so wonderful. Thank you!

2016-11-03 16:51 UTC, aurium commented on index.js
> +function setDefaultValues(parsedTmpl, values) {
I believe it is ok. Readability is important too!

2016-11-03 16:59 UTC, aurium commented on index.js
> +		if(!_.isString(obj) || !obj.match(helpRegex)) {
This place is better to allow poorly made templates to work fine.
Also, any JSON file can be used as template, and will respect the data type. So you are open to new use-cases like use this lib as a system tool to edit any JSON file. :grinning:

2016-11-03 17:04 UTC, aurium commented on test/config-template.test.js
> +var should = require('chai').should();
![oh stop it, you](https://cloud.githubusercontent.com/assets/30254/19976435/69a6b186-a1ce-11e6-9bd8-e0959c6c888c.png)

2016-11-27 18:55 UTC, merged